version: '3'

services:
  web:
    container_name: web_app_landing_page
    image: nginx:latest
    restart: always
    working_dir: /usr/share/nginx/html
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - .:/usr/share/nginx/html:rw

volumes:
  .:
    name: web_app_landing_page_volume
